#!/bin/bash
file=$1
touch $file.cc
NOW=$(date "+%Y.%m.%d %T")
echo "/**
 *    author:     stein
 *    created:    $NOW
**/
#include <bits/stdc++.h>

using namespace std;

int main() {
  ios::sync_with_stdio(false);
  cin.tie(nullptr);

  return 0;
}
" > $file.cc
echo created $fd at $NOW
